services:
  - type: web
    name: email-classifier-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT api.app:app
    autoDeploy: true
    envVars:
  - key: PYTHON_VERSION
    value: 3.10.12
